### ISSUE TITLE
withPigment causes tsconfig compiler path option to not work

### ISSUE THREAD

**Issue by inuwan** [mui/pigment-css#171]
### Steps to reproduce

1. With a Next.js 13+ project, configure withPigment in next.config.js
2. In the typescript tsconfig.json file, specify the compiler path option of 
`"paths":` {"src/*": ["./src/*"]},`
3. Add an import such as: 
`import {getStateName from 'src/common/utils'`
4 When compiling the next app, the error` EvalError: Cannot find module 'src/common/utils'` will be experienced
5. Eliminating withPigment will eliminate the error (but styles will be broken).  Changing the import to a relative path will correct the error

### Current behavior

Compiler error of `EvalError: Cannot find module `

### Expected behavior

No compiler error

### Context

Use a typescript remapped path

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: withPigment typescript path Next.js

**Comment by inuwan** [comment]
@brijeshb42 I'm using version 0.0.16 of @pigment-css/nextjs-plugin

**Comment by jpmaga** [comment]
I am getting the same error on nextjs 14 and 15. (didn't try 13)

tsconfig paths:
```json
    "paths": {
      "@/*": [
        "./src/*"
      ]
    },
```

and the following on a component:
```tsx
import { factory } from "@/lib/utils/factory"

const Flex = styled(factory.div)({
	"@layer base": {
		display: "flex",
	},
})
```

If I change the import line to `../../lib/utils/factory` it then works as expected.

I'm using `"@pigment-css/nextjs-plugin": "^0.0.17"`.

**Comment by brijeshb42** [comment]
Thanks everyone. I've found the issue and am currently working on a fix.

**Comment by brijeshb42** [comment]
@inuwan Can you try this build where I have tried to fix the issue. Instead of using `0.0.16` in the version, use this -

1. For `@pigment-css/react` - `@pigment-css/react@https://pkg.csb.dev/mui/pigment-css/commit/cfe48ebe/@pigment-css/react`
2. Fors @pigment-css/nextjs-plugin` - `@pigment-css/react@https://pkg.csb.dev/mui/pigment-css/commit/cfe48ebe/@pigment-css/nextjs-plugin`

**Comment by jpmaga** [comment]
For what is worth, this seems to mostly work. However, if you are in dev mode and change the path to "@/something/something" it it will produce the same error. A server restart fixes the issue.

**Comment by codemilli** [comment]
Same error as below

```
at Module.evaluate (/node_modules/@wyw-in-js/transform/lib/module.js:224:13)
    at evaluate (/node_modules/@wyw-in-js/transform/lib/evaluators/index.js:14:5)
    at BaseAction.evalFile (/node_modules/@wyw-in-js/transform/lib/transform/generators/evalFile.js:35:43)
```

**Comment by inuwan** [comment]
works for me

**Comment by jpmaga** [comment]
I found another issue related to this. If you import a component using "@/" (in my case, this is what i have in tsconfig) and try to use the sx prop on it, you get the same error. And then you have to go all the way up the three and remove wherever you have those imports and change them to relative paths.

**Comment by aleksakojadinovic** [comment]
Same problem when using pure js with `jsconfig` and `baseUrl` option.

```json
{
  "compilerOptions": {
    "baseUrl": "src"
  }
}
```

 In dev mode most changes require complete restart of the dev server, production builds fail for random baseUrl-relative imports.

**Comment by rhoiyds** [comment]
I'm getting the exact same problem. The behavior is isolated and definitely caused by pigment bundling.
Using @pigment-css/nextjs-plugin version 0.0.20.

Server restarts don't work as @jpmaga suggested.

@brijeshb42 Anything on getting that PR resolved?

**Comment by robinvdv12** [comment]
I'm having the same issues as described here.
Server restarts did work, but not anymore.

I'm using ` "@pigment-css/react": "^0.0.21"` and `"@pigment-css/nextjs-plugin": "^0.0.21"`.

**Comment by effektsvk** [comment]
Hello @brijeshb42 , I made a reproduction repo for this, the fix you pushed an hour ago did not help. I used the dependencies you sent to the PR.

The issue occurs when I'm reexporting `Grid` component from `@mui/material-pigment-css/Grid`. Check files `src/Components/Header/index.tsx` and `src/Components/Grid/index.tsx`.
To check if the issue still occurs, run `rm -rf .next && yarn build`.

https://github.com/effektsvk/pigment-css-repro-next-js

**Comment by valleywood** [comment]
Still getting problems even after upgrading to version 0.0.26 of `@pigment-css/react` 
See comment here with a simple reproduction example:
https://github.com/mui/pigment-css/pull/182#issuecomment-2464305672

**Comment by valleywood** [comment]
@brijeshb42 ⬆️  Do you think that information is enough? 🤔

**Comment by brijeshb42** [comment]
Let me check and get back

**Comment by valleywood** [comment]
Thanks @brijeshb42 can confirm all my aliases working again with version 0.0.27 👍

**Comment by valleywood** [comment]
@brijeshb42 

I was perhaps too early with the celebration the aliases are now working but now the EISDIR error is back with version 0.0.27 when I run `yarn build` 

Seems related to `pigment-css` since the error is referring to `@wyw-in-js` which is a subdependency

├─ @pigment-css/react@npm:0.0.27
│  └─ @wyw-in-js/transform@npm:0.5.5 (via npm:^0.5.5)
│
├─ @pigment-css/react@npm:0.0.27 [74622]
│  └─ @wyw-in-js/transform@npm:0.5.5 (via npm:^0.5.5)
│
├─ @pigment-css/react@npm:0.0.27 [abca8]
│  └─ @wyw-in-js/transform@npm:0.5.5 (via npm:^0.5.5)
│
└─ @pigment-css/unplugin@npm:0.0.25
   └─ @wyw-in-js/transform@npm:0.5.5 (via npm:^0.5.4)

```
 prefix: "error"
    err: {
      "type": "Error",
      "message": "EISDIR: illegal operation on a directory, read",
      "stack":
          Error: EISDIR: illegal operation on a directory, read
              at Object.readFileUtf8 (node:internal/fs/sync:25:18)
              at readFileSync (node:fs:441:19)
              at get code [as code] (/Project/node_modules/@wyw-in-js/transform/lib/transform/Entrypoint.helpers.js:111:99)
              at new Entrypoint (/Project/node_modules/@wyw-in-js/transform/lib/transform/Entrypoint.js:41:30)
              at Entrypoint.innerCreate (/Project/node_modules/@wyw-in-js/transform/lib/transform/Entrypoint.js:129:27)
              at /Project/node_modules/@wyw-in-js/transform/lib/transform/Entrypoint.js:85:47
              at EventEmitter.perf (/Project/node_modules/@wyw-in-js/transform/lib/utils/EventEmitter.js:45:20)
              at Entrypoint.create (/Project/node_modules/@wyw-in-js/transform/lib/transform/Entrypoint.js:84:25)
              at Entrypoint.createChild (/Project/node_modules/@wyw-in-js/transform/lib/transform/Entrypoint.js:176:23)
              at BaseAction.processImports (/Project/node_modules/@wyw-in-js/transform/lib/transform/generators/processImports.js:22:44)
              at processImports.next (<anonymous>)
              at /Project/node_modules/@wyw-in-js/transform/lib/transform/actions/BaseAction.js:66:78
              at EventEmitter.action (/Project/node_modules/@wyw-in-js/transform/lib/utils/EventEmitter.js:25:22)
              at BaseAction.emitAction (/Project/node_modules/@wyw-in-js/transform/lib/transform/actions/BaseAction.js:131:39)
              at nextFn (/Project/node_modules/@wyw-in-js/transform/lib/transform/actions/BaseAction.js:66:32)
              at processNext (/Project/node_modules/@wyw-in-js/transform/lib/transform/actions/BaseAction.js:111:28)
              at Object.next (/Project/node_modules/@wyw-in-js/transform/lib/transform/actions/BaseAction.js:120:9)
              at asyncActionRunner (/Project/node_modules/@wyw-in-js/transform/lib/transform/actions/actionRunner.js:39:102)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async asyncActionRunner (/Project/node_modules/@wyw-in-js/transform/lib/transform/actions/actionRunner.js:46:22)
              at async asyncActionRunner (/Project/node_modules/@wyw-in-js/transform/lib/transform/actions/actionRunner.js:46:22)
              at async asyncActionRunner (/Project/node_modules/@wyw-in-js/transform/lib/transform/actions/actionRunner.js:46:22)
              at async Object.transform (/Project/node_modules/@wyw-in-js/transform/lib/transform.js:107:20)
              at async Object.transform (/Project/node_modules/@pigment-css/unplugin/build/index.js:268:24)
              at async Object.transform (/Project/node_modules/unplugin/dist/webpack/loaders/transform.js:120:15)
    }
    
```

**Comment by brijeshb42** [comment]
Is this reproducible in this repo https://github.com/valleywood/pigment-css-repro-next-js ?

**Comment by brijeshb42** [comment]
Also, in the package versions, I see `@pigment-css/unplugin` v0.0.25 being used. It should be 27.

**Comment by valleywood** [comment]
@brijeshb42 Not reproduceable in the reproduction repo.
Just as described here in this thread https://github.com/mui/pigment-css/issues/164 and this thread https://github.com/mui/pigment-css/issues/211 the issue seems to be indeterministic :( 

So I'm really not sure whether this has to do with version `0.0.27` or not (probably not)

I also after multiple rebuilds of my project finally made the issue with  `EISDIR` go away again without doing any changes but wiping my `node_modules`, `.next` and `.yarn/cache`  followed by one or many `yarn build`s  🤯 🤷‍♂️ 

So to sum it ut it seems like aliases are working again now but the error with `EISDIR` seems to be remaining but unfortunately I've found now way to reproduce it consistently :(
