### ISSUE TITLE
Issue with @mui/utils package dependency

### ISSUE THREAD

**Issue by paulm17** [mui/pigment-css#309]
### Search keywords

vite build

### Latest version

- [X] I have tested the latest version

### Steps to reproduce

Build a package using @pigment/css react and use rollup.

### Current behavior

Without the vite sidestep.  I get the following issues:

> Uncaught SyntaxError: The requested module 'node_modules/prop-types/index.js' does not provide an export named 'default' (at elementAcceptingRef.js:1:8)

> Uncaught SyntaxError: The requested module 'node_modules/react-is/index.js' does not provide an export named 'ForwardRef' (at getDisplayName.js:1:10)

relevant links:
https://stackoverflow.com/a/44868718/439750
https://github.com/mui/material-ui/issues/18791
https://github.com/react-component/util/issues/105

### Expected behavior

These issues should not exist.

### Context

I'm using pigment-css as part of a custom UI library.  With tsup this issue isn't present.  However using rollup it is.

To sidestep the issue, I have added the following to my vite config:

```
optimizeDeps: {
    include: ['prop-types', 'react-is'],
  },
  resolve: {
    alias: {
      'prop-types': 'prop-types/prop-types.js',
      'react-is': 'react-is/cjs/react-is.development.js',
    },
  },
```

https://github.com/react-component/util/issues/105

**Comment by brijeshb42** [comment]
This is a known issue (mainly with Vite and indirectly Rollup) and will be fixed when we have the stable release (when we remove `prop-types` usage).
