### ISSUE TITLE
`styled` does not work with MUI system

### ISSUE THREAD

**Issue by siriwatknp** [mui/pigment-css#36]
### Search keywords

styled

### Latest version

- [X] I have tested the latest version

### Steps to reproduce

See https://github.com/mui/material-ui/actions/runs/8837080528/job/24265117421?pr=41663 in https://github.com/mui/material-ui/pull/41663

### Current behavior

`ownerState` is undefined in `InputBase` styles when `FilledInput` (Pigment) is wrapping `Input` (MUI System).

```js
const FilledInputRoot = styled(InputBase)(…)
```

The root cause is that FilledInputRoot does not forward `ownerState` to InputBase which causes an error from the InputBase.

### Expected behavior

They should work together, both MUI System wrappin Pigment or Pigment wrapping MUI System.

### Context

Found this issue when trying to migrate only FilledInput to support Pigment CSS.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by jbogedahl-st** [comment]
I believe I am hitting something similar... I am building a new next.js react app using app router and React Server Components. I found this awesome library and all the MUI - nextjs stuff that is coming together. I'm taking a gamble that MUI v6 with pigment-css will be released about the same time that I need it for this project (end of year 2024).

To see an example, I have created an app here: https://codesandbox.io/p/devbox/lively-snowflake-jc79t8

In this app, I have my layout, page and applicationHeader component all setup as RSC with appropriate styles, etc. I then embed a userProfileDropdown SSR / client component that uses material-ui emotion theming.  All of this seems to work fine, styles seem to be applied correctly in both RSC and client components. However, I'm hitting an error when trying to reference Material-UI theme values directly.  For example, my menu component will often be displayed inside modals, therefore, we bump up the z-index on the menu component to display correctly once in a modal. To do this, we grab the `theme.zindex.modal` value and add 10 to it.

I'm hitting a build error, because it is unable to find that value in my pigment-css theme. Is there a way to setup my application so that the pigment-css theme merges the material-ui theme, or can tell the build engine to ignore the material-ui theme variables?

The build error is:

``` 
TypeError: /project/workspace/src/components/menu.tsx: Cannot read properties of undefined (reading 'modal')
    at /project/workspace/src/components/menu.tsx:12:28
    at SxProcessor.processCss (/project/workspace/node_modules/@pigment-css/react/processors/sx.js:260:59)
    at SxProcessor.build (/project/workspace/node_modules/@pigment-css/react/processors/sx.js:162:22)
    at /project/workspace/node_modules/@wyw-in-js/transform/lib/plugins/collector.js:26:17
    at /project/workspace/node_modules/@wyw-in-js/transform/lib/utils/getTagProcessor.js:384:5
    at Array.forEach (<anonymous>)
    at applyProcessors (/project/workspace/node_modules/@wyw-in-js/transform/lib/utils/getTagProcessor.js:375:10)
    at /project/workspace/node_modules/@wyw-in-js/transform/lib/plugins/collector.js:25:42
    at EventEmitter.perf (/project/workspace/node_modules/@wyw-in-js/transform/lib/utils/EventEmitter.js:45:20)
    at collector (/project/workspace/node_modules/@wyw-in-js/transform/lib/plugins/collector.js:24:16)```

**Comment by jbogedahl-st** [comment]
> I'm hitting a build error, because it is unable to find that value in my pigment-css theme. Is there a way to setup my application so that the pigment-css theme merges the material-ui theme, or can tell the build engine to ignore the material-ui theme variables?

FYI... I did some digging and there is a `wyw-in-js.config.js` file. I was able to add a rule to ignore certain files for now. I feel like this is a work-around for the time being, would love some input from the team on how this will all be handled.

`wyw-in-js.config.js` contents (hopefully this doesn't override any defaults used with pigment-css):
```
/* eslint-disable eslint-comments/disable-enable-pair -- name is required by library */
/* eslint-disable check-file/filename-naming-convention -- name is required by library */
module.exports = {
	rules: [
		{
			// Excluding these files from wyw-in-js as it doesn't need to handle them and throws errors when it tries
			test: /[\\/]svgIcon.helpers.tsx|[\\/]menuDisplay.tsx/,
			action: 'ignore',
		},
	],
};
```
